### ISSUE TITLE
add test.sh and synthesize.sh

### ISSUE THREAD

**Issue by yt605155624** [yangdongchao/SoundStorm#10]
test.sh 输入是数据预处理测试集（两个文件，speaker 是训练集内的，因为测试集是 libritts `train-*` 分出来的）, 即 prompt 和 target 是同一个音频

synthesize.sh 输入 
1. prompt_semantic
2. prompt_acoustic 
3. target_semantic

3 个文件，即 prompt 和 target 可以不是同一个音频，那么可以进一步测试下集外的 speaker 的效果，这种情况下无法提供 target_acoustic, 因为是用 prompt 的音色说 target_semantic 的内容

2, 3 可以直接从输入 wav 中提取，可以

1. 直接输入 2 个文件
2. 直接从输入 wav 中提取

可以先实现 1 再实现 2，最终有 S1 模型后肯定是要用 2 的方法

**Comment by Firefang003** [comment]
@yt605155624  大佬，test.sh脚本已经更新了嘛，代码里面没看到吖

**Comment by yt605155624** [comment]
没，写完了 pr 会合入，issue 会自动关闭，着急可以自己先写 @Firefang003

**Comment by Firefang003** [comment]
@yt605155624 😅大佬，翻了几遍pr的commit还是没发现，给个链接地址？

**Comment by yt605155624** [comment]
@Firefang003 test.py push 到 pr 了 https://github.com/yangdongchao/SoundStorm/pull/13
