### ISSUE TITLE
您好，大佬，小白有个问题请教下

### ISSUE THREAD

**Issue by Firefang003** [yangdongchao/SoundStorm#2]
请问下acoustic_2.pth怎么保存，用什么读取音频获取，然后torch.save
![image](https://github.com/yangdongchao/SoundStorm/assets/127705756/79576943-bd61-4fd7-b506-9e84a64b7fe9)

**Comment by aixingxy** [comment]
refer to the Overview in readme

**Comment by yt605155624** [comment]
参考 https://github.com/yangdongchao/AcademiCodec/blob/master/egs/HiFi-Codec-24k-320d/infer.ipynb 不过可以选择合适的 codec 配置，比如这里应该选择 16k 的我猜测
